from PyQt5.QtWidgets import *
from PyQt5 import uic
from PyQt5.QtCore import *
import json
import client  as Client
import sys


# Qthread for checking for messages
class Listener_Thread(QThread):
    def __init__(self, parent=None):
        super().__init__(parent)

    # Signal Variable
    msg_stat = pyqtSignal(str)

    def run(self):
        # Variables from parent class
        cli = self.parent().client

        while True:
            user_id = self.parent().username_.text()
            msg = cli.recv_msg()
            data = json.loads(msg.decode())
            # Checks my user_id and message's user_id , we need to add msgs which are not generated by us
            user_id = self.parent().username_.text()
            if user_id != data["USERNAME"]:
                message = f"{data['USERNAME']} : {data['MESSAGE']} "
                # Emits the data
                self.msg_stat.emit(message)


# GUI Window Class
class Window(QMainWindow):
    def __init__(self):
        super(Window, self).__init__()
        self.thread = None

        # Loads .ui file
        uic.loadUi('UI\\Editing.ui', self)

        # gets the widgets from file to modify the widget
        self.scroll_area = self.findChild(QScrollArea, "scrollArea")
        self.scrollAreaWidgetContents = self.findChild(QWidget, "scrollAreaWidgetContents")
        self.button = self.findChild(QPushButton, "pushButton")
        self.edit = self.findChild(QLineEdit, "lineEdit")
        self.verticalLayout_4 = self.findChild(QVBoxLayout, "verticalLayout_4")
        self.scroll_area = self.findChild(QScrollArea, "scrollArea")
        self.username_ = self.findChild(QLineEdit, "lineEdit_3")
        self.edit_name = self.findChild(QPushButton, "pushButton_2")

        self.ip_label = self.findChild(QLabel, "label_2")
        self.ip_connection = self.findChild(QLineEdit, "lineEdit_2")
        self.connect_  = self.findChild(QPushButton, "pushButton_3")

        self.chatroom_label = self.findChild(QLabel, "label") 


        self.assign_name()
        self.username_.setEnabled(False)

        self.username = self.username_.text()
        self.enable_item(False)
        # Connecting button to a function
        self.edit_name.clicked.connect(self.change_state)
        self.button.clicked.connect(self.frame_msg)

        self.connect_.clicked.connect(self.init_connection)
    def enable_item(self, val):
        if val:
            self.chatroom_label.setText("Chatroom")
        else:
            self.chatroom_label.setText("Connection Pending ...")
        
        self.button.setEnabled(val)
        self.edit.setEnabled(val)

    def init_connection(self):
        self.client = Client.Connect_Init(self.ip_connection.text())
        self.enable_item(True)
        # Recv Thread
        self.Thread_init()
        self.ip_connection.hide()
        self.connect_.hide()
        self.ip_label.hide()

    def change_state(self):
        is_enabled = self.username_.isEnabled()
        if  is_enabled:
            self.assign_name(self.username_.text())
            self.username_.setEnabled(False)
            self.edit_name.setText("Edit")
        else:
            self.username_.setEnabled(True)
            self.edit_name.setText("Confirm")
        self.username = self.username_.text()

    def assign_name(self , name=None):
        if name:
            self.username_.setText(name)
            f = open('name.txt', 'w')
            f.write(name)
            f.close()
        else:
            f = open('name.txt', 'r')
            from random import choice
            name = choice(f.readlines())
            self.username_.setText(name)
            f.close()

    # Func to connect the Qthread class
    def Thread_init(self):
        self.thread = Listener_Thread(self) 
        self.thread.msg_stat.connect(self.add_msg)
        self.thread.start()

    # Clears text in lineEdit and retrieves the msg and Calls the func to add the msg to scrollArea
    def frame_msg(self):
        text = self.edit.text()
        data = f'{self.username} : {text}'
        self.edit.clear()
        self.add_msg(data, 1)
        self.client.Frame_POST('0', self.username, text)

    # Makes a Frame/Layout/Label and Adds the ScrollArea
    def add_msg(self, msg, me=0):
        frame = QFrame(self.scrollAreaWidgetContents)
        frame.setObjectName(u"frame")
        frame.setMinimumSize(QSize(0, 60))
        frame.setFrameShape(QFrame.StyledPanel)
        frame.setFrameShadow(QFrame.Raised)
        horizontalLayout = QHBoxLayout(frame)
        horizontalLayout.setObjectName(u"horizontalLayout_5")
        if me:
            label_2 = QLabel(frame)
            label_2.setObjectName(u"label_2")
            label_2.setMaximumSize(QSize(400, 16777215))
            label_2.setStyleSheet(u"background-color:  #F0EAEA;\n" \
                                  "border-radius: 13px;\n" \
                                  "padding: 15px;")
            label_2.setText(msg)

            if len(msg) > 50:
                label_2.setWordWrap(True)

            horizontalLayout.addWidget(label_2)

            horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

            horizontalLayout.addItem(horizontalSpacer)


            self.verticalLayout_4.addWidget(frame)
        else:
            label_2 = QLabel(frame)
            label_2.setObjectName(u"label_2")
            label_2.setMaximumSize(QSize(400, 16777215))
            label_2.setStyleSheet(u"background-color:  #F0EAEA;\n" \
                                  "border-radius: 13px;\n" \
                                  "padding: 15px;")
            label_2.setText(msg)
            

            if len(msg) > 50:
                label_2.setWordWrap(True)

            horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

            horizontalLayout.addItem(horizontalSpacer)
            horizontalLayout.addWidget(label_2)


            self.verticalLayout_4.addWidget(frame)

        
        max_value = self.scrollAreaWidgetContents.size().height()
        self.scroll_area.verticalScrollBar().setMaximum(max_value)
        self.scroll_area.verticalScrollBar().setValue(max_value)


# Runs the class only if it's the main file and not run while importing it !
if __name__ == "__main__":
    app = QApplication(sys.argv)
    win = Window()
    win.setWindowTitle("Messaging_Application")
    win.show()
    sys.exit(app.exec_())
